import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import EarthquakeDetails from '../components/EarthquakeDetails'
import { Inter } from 'next/font/google'
import { Almarai } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>الهزات الارضية</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.rtl.min.css" integrity="sha384-DOXMLfHhQkvFFp+rWTZwVlPVqdIhpDVYT9csOnHSgWQWPX0v5MCGtjCJbY6ERspU" crossorigin="anonymous">

        </link>
        <link href="https://fonts.googleapis.com/css?family=Readex+Pro:400|Almarai:400" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="py-5 text-center container">
          <div className="row py-lg-5">
            <div className="col-lg-6 col-md-8 mx-auto">
              <h3 className="fw-light">الهزات الأرضية الحالية حول العالم</h3>
              <p className="lead text-muted">
                تطوير عبدالواحد منصور              
              </p>

            </div>
          </div>
        </section>
        <EarthquakeDetails />
      </main>
    </>
  )
}
